apiVersion: v1
kind: Service
metadata:
  name: svc-node-project
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: node-project
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-node-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-project
  template:
    metadata:
      labels:
        app: node-project
    spec:
      containers:
        - name: node-app
          image: affandaudkhan/nodeapp:latest
          ports:
            - containerPort: 8080
