apiVersion: v1
kind: Service
metadata:
  name: node-project
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: node-project
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-project
  template:
    metadata:
      labels:
        app: node-project
    spec:
      containers:
        - name: node-project
          image: affandaudkhan/nodeapp:tagname
          ports:
            - containerPort: 80
